version: "3.8"
services:
  db:
    image: mysql:8.0.27
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: visual_dictionary
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - test_network

networks:
  test_network:
    driver: bridge