version: '3'
services:
  app:
    image: portfolio   # KotlinバックエンドアプリケーションのDockerイメージ
    build:
      context: ./backend                   # Dockerfileの場所（プロジェクトのルート）
    ports:
      - "8080:8080"                # ホストのポート8080をコンテナの8080にマッピング
    depends_on:
      - db                         # MySQLコンテナが先に起動するように設定
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/visual_dictionary
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: mysql:8.0               # MySQLのDockerイメージ
    environment:
      MYSQL_ROOT_PASSWORD: root     # rootユーザーのパスワード設定
      MYSQL_DATABASE: visual_dictionary # 作成したいデータベース名
    ports:
      - "3306:3306"                # ホストの3306ポートをMySQLの3306ポートにマッピング
    volumes:
      - db_data:/var/lib/mysql      # MySQLデータの永続化

volumes:
  db_data:
